version: 0.2

phases:
  build:
    commands:
      - echo "Building the project..."
      - mvn clean package  # Example build command, replace with your own

artifacts:
  files:
    - target/unicorn-web-project.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no

