version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      # Add any installation commands here
  build:
    commands:
      - echo Building the project...
      # Add your build commands here

artifacts:
  files:
    - target/unicorn-web-project.war   # Ensure this WAR file is correctly built
    - appspec.yml                      # Include the appspec.yml file
    - scripts/**/*                     # Include all files in the scripts directory
  discard-paths: no                    # Retain directory structure in the artifact

